from __future__ import annotations

EVIDENCE_ONLY_KINDS = {"RawEvidenceRef", "Prompt", "ToolUse", "ToolResult", "Turn", "Session", "App", "Repo", "Branch"}
SUPPORT_ONLY_KINDS = {"File", "Symbol", "Topic", "CleanedEvidenceWindow"}
ANSWER_SEED_KINDS = [
    "ReasoningNode",
    "DecisionUnit",
    "Decision",
    "WorkChange",
    "Fix",
    "Bug",
    "Blocker",
    "TestRun",
    "GitCommit",
    "Commit",
    "KnowledgeAtom",
    "KnowledgeVersion",
    "CodeNode",
    "Symbol",
]
RETRIEVAL_STOPWORDS = {
    "about",
    "after",
    "again",
    "also",
    "and",
    "are",
    "because",
    "been",
    "before",
    "being",
    "between",
    "but",
    "can",
    "could",
    "did",
    "does",
    "for",
    "from",
    "has",
    "have",
    "how",
    "into",
    "its",
    "not",
    "now",
    "only",
    "should",
    "that",
    "the",
    "then",
    "this",
    "use",
    "used",
    "using",
    "via",
    "was",
    "were",
    "what",
    "when",
    "where",
    "which",
    "why",
    "will",
    "with",
    "would",
}

__all__ = [
    "ANSWER_SEED_KINDS",
    "EVIDENCE_ONLY_KINDS",
    "RETRIEVAL_STOPWORDS",
    "SUPPORT_ONLY_KINDS",
]
