from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any


def add_peer_netd_start_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--node-id", default="amo-node", help="Stable AMO node id advertised by the sidecar.")
    parser.add_argument("--listen", default="/ip4/0.0.0.0/tcp/0", help="libp2p listen multiaddr.")
    parser.add_argument("--api", default="127.0.0.1:8788", help="Local sidecar API host:port. Must be fixed for managed start.")
    parser.add_argument("--store-path", default="", help="Optional sidecar JSONL inbox path. Defaults under AMO_HOME/.peer/netd.")
    parser.add_argument("--identity-key", default="", help="Optional persistent libp2p identity key path.")
    parser.add_argument(
        "--shared-secret-env",
        default="",
        help="Environment variable containing the shared HMAC secret used by peer-netd.",
    )
    parser.add_argument("--require-signature", action="store_true", help="Reject unsigned incoming peer envelopes.")
    parser.add_argument("--bootstrap", action="append", default=[], help="Bootstrap peer multiaddr. Repeat for multiple peers.")
    parser.add_argument("--static-relay", action="append", default=[], help="Circuit relay multiaddr. Repeat for multiple relays.")
    parser.add_argument(
        "--relay-profile",
        "--relay",
        dest="relay_profile",
        default="",
        help="Saved relay profile name. Expands to --static-relay, --auto-relay, --hole-punching, and rendezvous flags.",
    )
    parser.add_argument("--mdns", action="store_true", help="Enable LAN mDNS discovery.")
    parser.add_argument("--mdns-service", default="_amo-peer._udp", help="mDNS service tag.")
    parser.add_argument("--rendezvous-server", action="store_true", help="Serve AMO rendezvous registration/discovery streams.")
    parser.add_argument("--rendezvous-addr", default="", help="Rendezvous node multiaddr to register with after startup.")
    parser.add_argument("--rendezvous-namespace", default="", help="Rendezvous namespace to register this node under.")
    parser.add_argument("--rendezvous-ttl-seconds", type=int, default=7200, help="Rendezvous registration TTL.")
    parser.add_argument("--relay-service", action="store_true", help="Serve libp2p circuit relay v2 when reachable.")
    parser.add_argument("--nat-service", action="store_true", help="Help peers determine reachability.")
    parser.add_argument("--auto-relay", action="store_true", help="Enable AutoRelay; usually paired with --static-relay.")
    parser.add_argument("--hole-punching", action="store_true", help="Enable libp2p DCUtR hole punching.")
    parser.add_argument("--force-private", action="store_true", help="Force private reachability for relay tests.")
    parser.add_argument("--force-public", action="store_true", help="Force public reachability for relay-service tests.")
    parser.add_argument(
        "--advertise-localhost-dns",
        action="store_true",
        help="Local smoke only: advertise 127.0.0.1 as dns4/localhost.",
    )
    parser.add_argument(
        "--advertise-addr",
        action="append",
        default=[],
        help="Public libp2p listen multiaddr to advertise, e.g. /ip4/1.2.3.4/tcp/4001.",
    )
    parser.add_argument("--no-build", action="store_true", help="Do not build peer-netd automatically if the binary is missing.")


def add_peer_netd_watch_service_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--with-watch",
        action="store_true",
        help="Also install, uninstall, or inspect the peer-agent watch startup entry.",
    )
    parser.add_argument(
        "--watch-service-name",
        default="",
        help="Optional OS startup name for the peer-agent watch entry.",
    )


def add_peer_subcommands(sub: Any) -> None:
    peer = sub.add_parser("peer", help="Configure AMO peer rooms and the local libp2p sidecar")
    peer.add_argument("--amo-home", type=Path, help="AMO home directory containing peer config and room state.")
    peer_sub = peer.add_subparsers(dest="peer_command", required=True)
    peer_doctor_cmd = peer_sub.add_parser("doctor", help="Check peer identity, netd source, binary, sidecar, and peers")
    peer_doctor_cmd.add_argument("--strict", action="store_true", help="Return non-zero unless peer rooms are ready now.")
    peer_init = peer_sub.add_parser("init", help="Initialize this AMO node's peer identity")
    peer_init.add_argument("--node-id", required=True)
    peer_init.add_argument("--display-name", default="")
    peer_init.add_argument("--capability", action="append", default=[])
    peer_add = peer_sub.add_parser("add", help="Add a trusted peer identity and optional transport addresses")
    peer_add.add_argument("--node-id", required=True)
    peer_add.add_argument("--base-url", default="", help="Legacy direct HTTP URL, e.g. http://100.76.18.75:8787")
    peer_add.add_argument("--peer-id", default="", help="libp2p peer id for amo-peer-netd delivery.")
    peer_add.add_argument("--multiaddr", action="append", default=[], help="Dialable libp2p multiaddr. Repeat as needed.")
    peer_add.add_argument("--relay-addr", action="append", default=[], help="Dialable relay /p2p-circuit multiaddr. Repeat as needed.")
    peer_add.add_argument("--rendezvous-addr", default="", help="Rendezvous node multiaddr used for discovery.")
    peer_add.add_argument("--rendezvous-namespace", default="", help="Rendezvous namespace for this peer/group.")
    peer_add.add_argument("--display-name", default="")
    peer_add.add_argument("--capability", action="append", default=[])
    peer_add.add_argument("--trust", choices=["trusted", "limited", "blocked"], default="trusted")
    peer_add.add_argument(
        "--shared-secret-env",
        default="",
        help="Optional environment variable containing this peer's HMAC shared secret.",
    )
    peer_remove = peer_sub.add_parser("remove", help="Remove a configured peer identity")
    peer_remove.add_argument("--node-id", required=True)
    peer_sub.add_parser("status", help="Show peer node, policy, configured peers, and room count")
    peer_share = peer_sub.add_parser("share-card", help="Print or write this node's importable peer card")
    peer_share.add_argument("--out", type=Path, help="Optional JSON output path.")
    peer_share.add_argument("--base-url", default="", help="Optional legacy direct HTTP URL to include.")
    peer_share.add_argument("--rendezvous-addr", default="", help="Optional rendezvous node multiaddr to include.")
    peer_share.add_argument("--rendezvous-namespace", default="", help="Optional rendezvous namespace to include.")
    peer_share.add_argument("--relay-profile", "--relay", dest="relay_profile", default="", help="Saved relay profile to include in this card.")
    peer_import = peer_sub.add_parser("import-card", help="Import a trusted peer from a peer-card JSON file")
    peer_import.add_argument("--file", required=True, type=Path)
    peer_import.add_argument("--trust", choices=["trusted", "limited", "blocked"], default="trusted")
    peer_import.add_argument("--shared-secret-env", default="")
    peer_invite = peer_sub.add_parser("create-invite", help="Create a shareable peer invite bundle/code")
    peer_invite.add_argument("--out", type=Path, help="Optional JSON invite output path.")
    peer_invite.add_argument("--trust", choices=["trusted", "limited", "blocked"], default="trusted")
    peer_invite.add_argument("--shared-secret-env", default="")
    peer_invite.add_argument("--label", default="", help="Optional human-readable invite label.")
    peer_invite.add_argument("--base-url", default="", help="Optional legacy direct HTTP URL to include.")
    peer_invite.add_argument("--rendezvous-addr", default="", help="Optional rendezvous node multiaddr to include.")
    peer_invite.add_argument("--rendezvous-namespace", default="", help="Optional rendezvous namespace to include.")
    peer_invite.add_argument("--relay-profile", "--relay", dest="relay_profile", default="", help="Saved relay profile to include in this invite.")
    peer_invite.add_argument("--auto-approve", action="store_true", help="Auto-import the accepting peer after token proof.")
    peer_invite.add_argument("--expires-minutes", type=int, default=1440, help="Invite validity window.")
    peer_invite.add_argument("--max-uses", type=int, default=1, help="Maximum accepted join requests.")
    peer_accept = peer_sub.add_parser("accept-invite", help="Import an invite and optionally write this node's response card")
    peer_accept_source = peer_accept.add_mutually_exclusive_group(required=True)
    peer_accept_source.add_argument("--file", type=Path, help="Invite JSON file to accept.")
    peer_accept_source.add_argument("--code", default="", help="amo-peer-invite: code to accept.")
    peer_accept.add_argument("--trust", choices=["trusted", "limited", "blocked"], default="")
    peer_accept.add_argument("--shared-secret-env", default="")
    peer_accept.add_argument("--response-out", type=Path, help="Optional response peer-card JSON path to send back.")
    peer_accept.add_argument("--no-send-join-request", action="store_true", help="Do not send the automatic return join request.")
    peer_join_requests = peer_sub.add_parser("join-requests", help="List pending peer join requests")
    peer_join_requests.add_argument("--status", default="", choices=["", "pending", "approved", "rejected"])
    peer_approve_join = peer_sub.add_parser("approve-join", help="Approve a pending peer join request")
    peer_approve_join.add_argument("--request-id", required=True)
    peer_reject_join = peer_sub.add_parser("reject-join", help="Reject a pending peer join request")
    peer_reject_join.add_argument("--request-id", required=True)
    peer_reject_join.add_argument("--reason", default="")
    peer_sub.add_parser("rooms", help="List local peer investigation rooms")
    peer_context = peer_sub.add_parser("context", help="Build the three-layer context pack for a room")
    peer_context.add_argument("--room-id", required=True)
    peer_context.add_argument("--viewer-node-id", default="", help="Defaults to this AMO node id")
    peer_message = peer_sub.add_parser("append-message", help="Append a local peer-room message for smoke tests/manual use")
    peer_message.add_argument("--room-id", required=True)
    peer_message.add_argument("--from-node-id", required=True)
    peer_message.add_argument("--to-node-id", action="append", default=[])
    peer_message.add_argument("--type", default="context_request")
    peer_message.add_argument("--content", required=True)
    peer_message.add_argument("--citation", action="append", default=[])
    peer_message.add_argument("--confidence", type=float)
    peer_message.add_argument("--audience", choices=["peer", "group", "initiator", "local"], default="")
    peer_send = peer_sub.add_parser("send-message", help="Append and send a room message through amo-peer-netd")
    peer_send.add_argument("--room-id", required=True)
    peer_send.add_argument("--peer-id", required=True, help="Configured AMO peer node id, not the libp2p peer id.")
    peer_send.add_argument("--type", default="context_request")
    peer_send.add_argument("--content", required=True)
    peer_send.add_argument("--citation", action="append", default=[])
    peer_send.add_argument("--confidence", type=float)
    peer_send.add_argument("--audience", choices=["peer", "group", "initiator", "local"], default="")
    peer_summary = peer_sub.add_parser("update-summary", help="Replace a room's initiator-owned rolling summary")
    peer_summary.add_argument("--room-id", required=True)
    peer_summary.add_argument("--summary", required=True)
    peer_room = peer_sub.add_parser("open-room", help="Create an investigation room and invite configured peers")
    peer_room.add_argument("--topic", required=True)
    peer_room.add_argument("--peer", action="append", default=[], help="Peer node id to invite. Repeat for multiple peers.")
    peer_room.add_argument("--no-send", action="store_true", help="Create the room locally without sending invites.")
    peer_setup = peer_sub.add_parser("setup", help="One-time peer setup: init identity, start relay sidecar, and optionally install startup")
    add_peer_netd_start_args(peer_setup)
    peer_setup.add_argument("--display-name", default="", help="Display name to save for this AMO peer identity.")
    peer_setup.add_argument("--capability", action="append", default=[], help="Capability to save on first setup. Repeat as needed.")
    peer_setup.add_argument("--relay-addr", default="", help="Relay multiaddr to save before starting, e.g. from the AWS relay output.")
    peer_setup.add_argument("--namespace", default="", help="Rendezvous namespace to save with --relay-addr.")
    peer_setup.add_argument("--profile-name", default="", help="Profile name to save when --relay-addr is provided. Defaults to --relay/--relay-profile or default.")
    peer_setup_invite = peer_setup.add_mutually_exclusive_group()
    peer_setup_invite.add_argument("--invite", type=Path, help="Invite JSON to accept after relay startup.")
    peer_setup_invite.add_argument("--invite-code", default="", help="amo-peer-invite: code to accept after relay startup.")
    peer_setup.add_argument("--install-startup", action="store_true", help="Install OS startup entries for sidecar and peer-agent watch.")
    peer_setup.add_argument("--service-name", default="AMO Peer Netd")
    add_peer_netd_watch_service_args(peer_setup)
    peer_setup.add_argument("--no-start", action="store_true", help="Only save config/profile; do not start peer-netd now.")
    peer_enable = peer_sub.add_parser("enable", help="Build if needed and start the managed libp2p sidecar")
    add_peer_netd_start_args(peer_enable)
    peer_netd = peer_sub.add_parser("netd", help="Build, start, stop, and inspect the managed libp2p sidecar")
    peer_netd_sub = peer_netd.add_subparsers(dest="netd_command", required=True)
    peer_netd_build = peer_netd_sub.add_parser("build", help="Compile amo-peer-netd into AMO_HOME/.peer/bin")
    peer_netd_build.add_argument("--out", type=Path, help="Optional output binary path.")
    peer_netd_start = peer_netd_sub.add_parser("start", help="Start the managed libp2p sidecar")
    add_peer_netd_start_args(peer_netd_start)
    peer_netd_sub.add_parser("stop", help="Stop the managed libp2p sidecar")
    peer_netd_sub.add_parser("status", help="Show managed libp2p sidecar process and health state")
    peer_netd_install = peer_netd_sub.add_parser("install-service", help="Plan or install OS startup for peer netd")
    add_peer_netd_start_args(peer_netd_install)
    peer_netd_install.add_argument("--service-name", default="AMO Peer Netd")
    add_peer_netd_watch_service_args(peer_netd_install)
    peer_netd_install.add_argument("--apply", action="store_true", help="Actually create the OS startup entry.")
    peer_netd_uninstall = peer_netd_sub.add_parser("uninstall-service", help="Plan or remove OS startup for peer netd")
    peer_netd_uninstall.add_argument("--service-name", default="AMO Peer Netd")
    add_peer_netd_watch_service_args(peer_netd_uninstall)
    peer_netd_uninstall.add_argument("--apply", action="store_true", help="Actually remove the OS startup entry.")
    peer_netd_service_status_cmd = peer_netd_sub.add_parser("service-status", help="Inspect the OS startup entry for peer netd")
    peer_netd_service_status_cmd.add_argument("--service-name", default="AMO Peer Netd")
    add_peer_netd_watch_service_args(peer_netd_service_status_cmd)
    peer_relay = peer_sub.add_parser("relay", help="Run or inspect a public AMO relay+rendezvous helper node")
    peer_relay_sub = peer_relay.add_subparsers(dest="relay_command", required=True)
    peer_relay_start = peer_relay_sub.add_parser("start", help="Start a combined circuit relay and rendezvous node")
    peer_relay_start.add_argument("--node-id", default="amo-relay")
    peer_relay_start.add_argument("--listen", default="/ip4/0.0.0.0/tcp/4001")
    peer_relay_start.add_argument("--api", default="127.0.0.1:8798")
    peer_relay_start.add_argument("--advertise-addr", action="append", default=[], help="Public libp2p multiaddr, e.g. /ip4/1.2.3.4/tcp/4001")
    peer_relay_start.add_argument("--namespace", default="amo-peer-default", help="Suggested rendezvous namespace for this trust group.")
    peer_relay_start.add_argument("--store-path", default="")
    peer_relay_start.add_argument("--no-build", action="store_true")
    peer_relay_save = peer_relay_sub.add_parser("save", help="Save a client relay profile for short --relay commands")
    peer_relay_save.add_argument("--name", required=True)
    peer_relay_save.add_argument("--addr", required=True, help="Relay/rendezvous multiaddr.")
    peer_relay_save.add_argument("--rendezvous-addr", default="", help="Optional distinct rendezvous multiaddr. Defaults to --addr.")
    peer_relay_save.add_argument("--namespace", required=True, help="Rendezvous namespace for this trust group.")
    peer_relay_save.add_argument("--no-auto-relay", action="store_true", help="Do not enable AutoRelay when this profile is used.")
    peer_relay_save.add_argument("--no-hole-punching", action="store_true", help="Do not enable hole punching when this profile is used.")
    peer_relay_show = peer_relay_sub.add_parser("show", help="Show one saved client relay profile")
    peer_relay_show.add_argument("--name", required=True)
    peer_relay_delete = peer_relay_sub.add_parser("delete", help="Delete one saved client relay profile")
    peer_relay_delete.add_argument("--name", required=True)
    peer_relay_sub.add_parser("list", help="List saved client relay profiles")
    peer_relay_sub.add_parser("status", help="Show the managed relay/rendezvous node status")
    peer_poll_netd = peer_sub.add_parser("poll-netd", help="Process delivered sidecar messages into local peer rooms")
    peer_poll_netd.add_argument("--limit", type=int, default=None)
    peer_poll_netd.add_argument("--watch", action="store_true", help="Keep polling the sidecar inbox until interrupted.")
    peer_poll_netd.add_argument("--interval-seconds", type=float, default=2.0)
    peer_poll_netd.add_argument("--max-iterations", type=int, default=0, help="Testing/debug guard for --watch. 0 means forever.")
    peer_poll_netd.add_argument("--fail-fast", action="store_true", help="In watch mode, exit on the first poll error.")
    peer_serve = peer_sub.add_parser("serve", help="Run the direct peer listener for Tailscale/private networking")
    peer_serve.add_argument("--host", default="0.0.0.0")
    peer_serve.add_argument("--port", type=int, default=8787)

    peer_agent = sub.add_parser("peer-agent", help="Run AMO peer-agent ask/watch/finalize workflows")
    peer_agent.add_argument("--amo-home", type=Path, help="AMO home directory for peer-agent state.")
    peer_agent_sub = peer_agent.add_subparsers(dest="peer_agent_command", required=True)
    peer_agent_ask = peer_agent_sub.add_parser("ask", help="Ask local memory first, then open a peer room if needed")
    peer_agent_ask.add_argument("--query", required=True)
    peer_agent_ask.add_argument("--peer", action="append", default=[], help="Trusted peer node id to ask. Repeat for multiple peers.")
    peer_agent_ask.add_argument("--session-id", default="")
    peer_agent_ask.add_argument("--min-confidence", type=float, default=None)
    peer_agent_ask.add_argument("--timeout-seconds", type=float, default=None)
    peer_agent_ask_room = peer_agent_sub.add_parser("ask-room", help="Send a schema-valid follow-up request inside an existing peer room")
    peer_agent_ask_room.add_argument("--room-id", required=True)
    peer_agent_ask_room.add_argument("--query", required=True)
    peer_agent_ask_room.add_argument("--peer", action="append", default=[], help="Trusted peer node id to ask. Defaults to room peers.")
    peer_agent_ask_room.add_argument("--session-id", default="")
    peer_agent_ask_room.add_argument("--min-confidence", type=float, default=None)
    peer_agent_ask_room.add_argument("--timeout-seconds", type=float, default=None)
    peer_agent_ask_room.add_argument(
        "--wait-for-response",
        action="store_true",
        help="After sending the follow-up, drain peer-agent inbox until targeted peer responses arrive or timeout.",
    )
    peer_agent_continue = peer_agent_sub.add_parser("continue", help="Let the initiator planner choose one next room action")
    peer_agent_continue.add_argument("--room-id", required=True)
    peer_agent_continue.add_argument("--min-confidence", type=float, default=None)
    peer_agent_continue.add_argument("--timeout-seconds", type=float, default=None)
    peer_agent_watch = peer_agent_sub.add_parser("watch", help="Drain peer inbox and respond/finalize rooms")
    peer_agent_watch.add_argument("--interval-seconds", type=float, default=2.0)
    peer_agent_watch.add_argument("--max-iterations", type=int, default=0, help="Testing/debug guard. 0 means forever.")
    peer_agent_watch.add_argument("--limit", type=int, default=None, help="Maximum netd envelopes to drain per tick.")
    peer_agent_watch.add_argument("--fail-fast", action="store_true")
    peer_agent_status = peer_agent_sub.add_parser("status", help="Show peer-agent room state")
    peer_agent_status.add_argument("--room-id", required=True)
    peer_agent_context = peer_agent_sub.add_parser("context", help="Show local peer-agent room context")
    peer_agent_context.add_argument("--room-id", required=True)
    peer_agent_messages = peer_agent_sub.add_parser("messages", help="Show peer-agent room messages")
    peer_agent_messages.add_argument("--room-id", required=True)
    peer_agent_summary = peer_agent_sub.add_parser("summarize", help="Update an initiator-owned room summary")
    peer_agent_summary.add_argument("--room-id", required=True)
