from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from .constants import CODEX_MCP_NAME
from .constants import MANAGED_BEGIN
from .constants import MANAGED_END
from .constants import SKILL_CHECKPOINT_MARKER


def write_runtime_config(amo_home: Path, resolved_models: dict[str, str]) -> str:
    payload = _runtime_config_payload(resolved_models)
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def _config_operation(*, amo_home: Path, resolved_models: dict[str, str]) -> dict[str, Any]:
    path = amo_home / "config.json"
    return {
        "target": "amo",
        "path": str(path),
        "exists": path.exists(),
        "after": write_runtime_config(amo_home, resolved_models),
        "description": "Persist AMO runtime/model configuration.",
    }


def _hook_launcher_operation(*, launcher_path: Path) -> dict[str, Any]:
    return {
        "target": "amo-hook-launcher",
        "path": str(launcher_path),
        "exists": launcher_path.exists(),
        "after": _hook_launcher_script(),
        "description": "Write a standalone hook launcher that works from Codex hook sandboxes.",
    }


def _hook_launcher_script() -> str:
    import_root = Path(__file__).resolve().parents[2]
    return (
        "# Generated by Agent Memory Orchestrator. Do not edit.\n"
        "from __future__ import annotations\n\n"
        "import json\n"
        "import runpy\n"
        "import sys\n"
        "from pathlib import Path\n\n"
        f"IMPORT_ROOT = Path({json.dumps(str(import_root))})\n"
        "if str(IMPORT_ROOT) not in sys.path:\n"
        "    sys.path.insert(0, str(IMPORT_ROOT))\n\n"
        "try:\n"
        "    runpy.run_module('agent_memory_orchestrator.runtime.hook.launcher', run_name='__main__')\n"
        "except SystemExit as exc:\n"
        "    if exc.code in (0, None):\n"
        "        raise\n"
        "    print(json.dumps({\n"
        "        'continue': True,\n"
        "        'systemMessage': f'AMO hook launcher failed open: SystemExit: {exc.code}',\n"
        "    }, indent=2))\n"
        "    raise SystemExit(0)\n"
        "except BaseException as exc:\n"
        "    print(json.dumps({\n"
        "        'continue': True,\n"
        "        'systemMessage': f'AMO hook launcher failed open: {type(exc).__name__}: {exc}',\n"
        "    }, indent=2))\n"
        "    raise SystemExit(0)\n"
    )


def _runtime_config_payload(resolved_models: dict[str, str]) -> dict[str, Any]:
    return {
        "schema_version": 1,
        "local_only": True,
        "db_path": ".data/codex_live_memory.db",
        "retrieval_db_path": ".data/retrieval.sqlite",
        "export_dir": "exports",
        "graph_backend": "kuzu",
        "graph_path": ".graph/amo.kuzu",
        "retrieval_graph_path": "",
        "retrieval_graph_scope": "",
        "evidence_dir": ".evidence",
        "qwen_runtime": "ollama",
        "qwen_model": resolved_models["qwen_model"],
        "qwen_endpoint": "http://127.0.0.1:11434",
        "qwen_timeout_seconds": 20,
        "qwen_planner_timeout_seconds": 8,
        "qwen_extract_timeout_seconds": 25,
        "qwen_compress_timeout_seconds": 12,
        "qwen_num_ctx": 2048,
        "drain_max_windows_per_run": 3,
        "auto_drain_enabled": True,
        "auto_drain_interval_seconds": 8,
        "auto_drain_record_limit": 500,
        "auto_retrieval_node_limit": 10000,
        "auto_retrieval_max_doc_chars": 5000,
        "auto_embedding_batch_size": 10000,
        "approval_mode": "manual",
        "embedding_model": resolved_models["embedding_model"],
        "embedding_dims": 1024 if resolved_models["embedding_model"] == "BAAI/bge-m3" else 384,
        "reranker_backend": "cross-encoder",
        "reranker_model": resolved_models["reranker_model"],
        "vector_backend": resolved_models["vector_backend"],
        "model_preset": resolved_models["preset"],
    }

def _codex_skill_checkpoint_skill(*, amo_home: Path, python_command: str) -> str:
    command = _skill_checkpoint_mark_command(python_command, "codex", amo_home, note_placeholder="<user note>")
    return (
        "---\n"
        "name: amo-skill-checkpoint\n"
        "description: Use when the user types /skill-checkpoint or asks to turn the current workflow into a reusable AMO skill checkpoint.\n"
        "---\n\n"
        f"<!-- {SKILL_CHECKPOINT_MARKER}: codex -->\n\n"
        "# AMO Skill Checkpoint\n\n"
        "When the user asks for `/skill-checkpoint`, do not summarize the session manually and do not call sub-agents.\n\n"
        "Run one local AMO marker command from the current workspace:\n\n"
        "```powershell\n"
        f"{command}\n"
        "```\n\n"
        "Replace `<user note>` with the user's checkpoint note if provided. If no note is provided, omit `--note` or pass an empty note.\n\n"
        "After the command returns, report only the `checkpoint_id` and marker path. AMO hooks already captured the surrounding prompts, tool calls, tool results, code reads, patches, commits, and validation evidence.\n"
    )


def _claude_skill_checkpoint_command(*, amo_home: Path, python_command: str) -> str:
    command = _skill_checkpoint_mark_command(python_command, "claude", amo_home, note_placeholder="$ARGUMENTS")
    return (
        "---\n"
        "description: Mark the current AMO session as a reusable skill checkpoint\n"
        "---\n\n"
        f"<!-- {SKILL_CHECKPOINT_MARKER}: claude -->\n\n"
        "Mark the current AMO session as a pending skill checkpoint. Do not summarize the session manually.\n\n"
        "Run this command from the current workspace:\n\n"
        "```bash\n"
        f"{command}\n"
        "```\n\n"
        "Then reply with the `checkpoint_id`, marker path, and that AMO will build the compact packet later from captured hook evidence.\n"
    )


def _skill_checkpoint_mark_command(
    python_command: str,
    agent: str,
    amo_home: Path,
    *,
    note_placeholder: str,
) -> str:
    note = note_placeholder.replace('"', '\\"')
    return (
        f'{_shell_command_atom(python_command)} -m agent_memory_orchestrator.runtime.cli.main '
        f'skill-checkpoint mark --agent {agent} --amo-home "{amo_home}" --note "{note}"'
    )

def _codex_managed_block(*, amo_home: Path, python_command: str) -> str:
    mcp_args = ["-m", "agent_memory_orchestrator.runtime.mcp.server", "--amo-home", str(amo_home)]
    lines = [
        MANAGED_BEGIN,
        "# Managed by Agent Memory Orchestrator. Do not edit inside this block.",
        f"[mcp_servers.{CODEX_MCP_NAME}]",
        f"command = {_toml_string(python_command)}",
        f"args = {_toml_array(mcp_args)}",
        "",
    ]
    lines.append("# Codex command hooks are managed in ~/.codex/hooks.json for VS Code compatibility.")
    lines.append(MANAGED_END)
    return "\n".join(lines)


def _hook_events() -> list[tuple[str, str, str]]:
    return [
        ("SessionStart", "startup|resume|clear", "AMO starting graph capture"),
        ("UserPromptSubmit", "", "AMO capturing prompt evidence"),
        ("PostToolUse", "*", "AMO capturing tool evidence"),
        ("Stop", "", "AMO capturing session stop"),
    ]


def _hook_command(
    python_command: str,
    agent: str,
    amo_home: Path,
    *,
    hook_launcher: Path | None = None,
) -> str:
    if hook_launcher is not None:
        return f'{_shell_command_atom(python_command)} "{hook_launcher}" --agent {agent} --amo-home "{amo_home}"'
    return (
        f'{_shell_command_atom(python_command)} -m agent_memory_orchestrator.runtime.hook.launcher '
        f'--agent {agent} --amo-home "{amo_home}"'
    )


def _shell_command_atom(value: str) -> str:
    if value.startswith('"') or value.startswith("'"):
        return value
    if re.search(r"\s", value):
        return f'"{value}"'
    return value

def _toml_string(value: str) -> str:
    return json.dumps(value)


def _toml_array(values: list[str]) -> str:
    return "[" + ", ".join(_toml_string(value) for value in values) + "]"
