"""Versioned central-memory edge contracts."""

from __future__ import annotations

VERSION_OF = "VERSION_OF"
DERIVED_FROM_SESSION_NODE = "DERIVED_FROM_SESSION_NODE"
DERIVED_FROM_PACKET = "DERIVED_FROM_PACKET"
SUPPORTED_BY_EVIDENCE = "SUPPORTED_BY_EVIDENCE"
IMPLEMENTED_BY_COMMIT = "IMPLEMENTED_BY_COMMIT"
TOUCHES_FILE = "TOUCHES_FILE"
TOUCHES_SYMBOL = "TOUCHES_SYMBOL"
DUPLICATE_OF = "DUPLICATE_OF"
REFINES = "REFINES"
SUPERSEDES = "SUPERSEDES"
CONFLICTS_WITH = "CONFLICTS_WITH"
REVERTS = "REVERTS"
RELATED_REVIEW = "RELATED_REVIEW"
STATUS_CHANGED = "STATUS_CHANGED"
GRAPH_VIEW_AT = "GRAPH_VIEW_AT"

VERSION_RELATIONS = frozenset(
    {
        VERSION_OF,
        DERIVED_FROM_SESSION_NODE,
        DERIVED_FROM_PACKET,
        SUPPORTED_BY_EVIDENCE,
        IMPLEMENTED_BY_COMMIT,
        TOUCHES_FILE,
        TOUCHES_SYMBOL,
    }
)
DECISION_REVIEW_RELATIONS = frozenset({DUPLICATE_OF, REFINES, SUPERSEDES, CONFLICTS_WITH, RELATED_REVIEW})
STATUS_RELATIONS = frozenset({STATUS_CHANGED})
GRAPH_VIEW_RELATIONS = frozenset({GRAPH_VIEW_AT})


def is_decision_review_relation(kind: str) -> bool:
    return str(kind or "") in DECISION_REVIEW_RELATIONS


__all__ = [
    "CONFLICTS_WITH",
    "DECISION_REVIEW_RELATIONS",
    "DERIVED_FROM_PACKET",
    "DERIVED_FROM_SESSION_NODE",
    "DUPLICATE_OF",
    "GRAPH_VIEW_AT",
    "GRAPH_VIEW_RELATIONS",
    "IMPLEMENTED_BY_COMMIT",
    "REFINES",
    "RELATED_REVIEW",
    "REVERTS",
    "STATUS_CHANGED",
    "STATUS_RELATIONS",
    "SUPERSEDES",
    "SUPPORTED_BY_EVIDENCE",
    "TOUCHES_FILE",
    "TOUCHES_SYMBOL",
    "VERSION_OF",
    "VERSION_RELATIONS",
    "is_decision_review_relation",
]
